### PR TITLE
feat: Add node device API endpoint interaction

### PR DESCRIPTION
**Pull request by sachin120**
#### What does this implement
added API for node device 

**Node Devices**
- **GET:** list of node devices for a given systemID
-------
**Node Device**
- **GET:** get node device with given systemID and device ID
- **DELETE:** Delete the device with the given systemID and device ID

### CODE REVIEW

**Review by troyanov — APPROVED** [review]
Hi @sachin120 and thank you for the contribution!

May I ask you about your use case? Why do you need to have this API functionality available in the client?

**Comment by sachin120** [comment]
Hi @troyanov 
we want to list GPU which are listed under PCI Devices for node. we are using this go client for the rest of our operations.

**Review by skatsaounis — CHANGES_REQUESTED** [review]
LGTM after some changes that I am suggesting. The most important is the NodeDeviceBus enumeration suggestion, since without it we will return erroneous results.

Happy to merge when you take care of them :slightly_smiling_face:

**Review by skatsaounis — APPROVED** [review]
LGTM +1 and thank you for the changes :slightly_smiling_face:

**Pull request merged**
