### PR TITLE
feat: allow resource pool to work with name or id

### PR DESCRIPTION
**Pull request by sachin120**

### CODE REVIEW

**Comment by sachin120** [comment]
Hi @skatsaounis 
can you pls review this once

**Comment by troyanov** [comment]
This change will break things for existing users and it would be great if we can avoid this.
I confirm that API indeed works for `id` and `name`, so for example these requests will return the same result:
`http://10.0.0.37:5240/MAAS/api/2.0/resourcepool/0/`
`http://10.0.0.37:5240/MAAS/api/2.0/resourcepool/name/`

But maybe instead of changing existing functions signature we can add new methods?
```go
GetByName(name string) (*entity.ResourcePool, error)
UpdateByName(name string, params *entity.ResourcePoolParams) (*entity.ResourcePool, error)
DeleteByName(name string) error
```

**Comment by sachin120** [comment]
I have added those methods with separate functions as suggested.

**Review by skatsaounis — APPROVED** [review]
LGTM +1. However, I am thinking of it more as an extension rather than a bug. I will update the title and merge. Thank you @sachin120 for the contribution :slightly_smiling_face:

**Pull request merged**
